--[[

│تم تطوير وبرمجة السورس من قبل جاك ✾ .
│@ V_P_E
#-------------------------------------------------------------------
]]

local function jacka(msg,MsgText)
if msg.type ~= "pv" then
if MsgText[1] == "زخرفه" then
redis:setex(debo..":jackNow:"..msg.sender_user_id_,500,true)
sendMsg(msg.chat_id_,msg.id_,"| حسننا , الان يمكنك ارسال الاسم ولبعض الرموز المميزه اكتب رموز")    
return false
end

if redis:get(debo..":jackNow:"..msg.sender_user_id_) then
redis:del(debo..":jackNow:"..msg.sender_user_id_)
if utf8.len(msg.text) > 300 then
sendMsg(msg.chat_id_,msg.id_,"| لا يمكنك زخرفه اكثر من 20 حرف \n| ارسل امر زخرفه وحاول مجددا بحروف اقل")    
return false
elseif msg.text:match("\n") then
sendMsg(msg.chat_id_,msg.id_,"| لا يمكن زخرفه نص يحتوي على اكثر من سطر .")
return false
end
local EmojeS = {
' 𓁻',
' 𓏴  ',
' 𓏶 ',
' 𓏡',
' 𓏢', 
' 𓏣', 
' ☽‘',
' 𖠱²²', 
'▽', 
' 𖡛“', 
' 𖡚℡', 
' 𖡨', 
}

local Emoje = {
' ♕',
' 𖤍',
'˛𖤓',
' ཻ ☫',
' ♫ ',
' 𖠶 ',
' 𖠲',
' 𖡥',
'  ☬',
' 𖤐',
' 𓇼',
' ♘  '
}


local jack = Text:gsub('ض','ضِٰـِۢ')
jack = jack:gsub('ص','صِٰـِۢ')
jack = jack:gsub('ث','ثِٰـِۢ')
jack = jack:gsub('ق','قِٰـِۢ')
jack = jack:gsub('ف','فِٰ͒ـِۢ')
jack = jack:gsub('غ','غِٰـِۢ')
jack = jack:gsub('ع','عِٰـِۢ')
jack = jack:gsub('خ','خِٰ̐ـِۢ')
jack = jack:gsub('ح','حِٰـِۢ')
jack = jack:gsub('ج','جِٰـِۢ')
jack = jack:gsub('ش','شِٰـِۢ')
jack = jack:gsub('س','سِٰـِۢ')
jack = jack:gsub('ي','يِٰـِۢ')
jack = jack:gsub('ب','بِٰـِۢ')
jack = jack:gsub('ل','لِٰـِۢ')
jack = jack:gsub('ا','آ')
jack = jack:gsub('ت','تِٰـِۢ')
jack = jack:gsub('ن','نِٰـِۢ')
jack = jack:gsub('م','مِٰـِۢ')
jack = jack:gsub('ك','ڪِٰـِۢ')
jack = jack:gsub('ط','طِٰـِۢ')
jack = jack:gsub('ظ','ظِٰـِۢ')
jack = jack:gsub('ء','ء')
jack = jack:gsub('ؤ','ؤ')
jack = jack:gsub('ر','ر')
jack = jack:gsub('ى','ى')
jack = jack:gsub('ز','ز')
jack = jack:gsub('و','ﯛ̲୭')
jack = jack:gsub('ه','ۿۿہ')
jack = jack:gsub('a','𝗮')
jack = jack:gsub('A','𝗔')
jack = jack:gsub("b","𝗯")
jack = jack:gsub("B","𝗕")
jack = jack:gsub("c","𝗰")
jack = jack:gsub("C","𝗖")
jack = jack:gsub("d","𝗱")
jack = jack:gsub("D","𝗗")
jack = jack:gsub("e","𝗲")
jack = jack:gsub("E","𝗘")
jack = jack:gsub("f","𝗳")
jack = jack:gsub("F","𝗙")
jack = jack:gsub("g","𝗴")
jack = jack:gsub("G","𝗚")
jack = jack:gsub("h","𝗵")
jack = jack:gsub("H","𝗛")
jack = jack:gsub("i","𝗹")
jack = jack:gsub("I","𝗜")
jack = jack:gsub("j","𝗝")
jack = jack:gsub("J","𝗝")
jack = jack:gsub("k","𝗸")
jack = jack:gsub("K","𝗞")
jack = jack:gsub("l","𝗹")
jack = jack:gsub("L","𝗟")
jack = jack:gsub("m","𝗺")
jack = jack:gsub("M","𝗠")
jack = jack:gsub("n","𝗻")
jack = jack:gsub("N","𝗡")
jack = jack:gsub("o","𝗼")
jack = jack:gsub("O","𝗢")
jack = jack:gsub("p","𝗽")
jack = jack:gsub("P","𝗣")
jack = jack:gsub("q","𝗾")
jack = jack:gsub("Q","𝗤")
jack = jack:gsub("r","𝗿")
jack = jack:gsub("R","𝗥")
jack = jack:gsub("s","𝘀")
jack = jack:gsub("S","𝗦")
jack = jack:gsub("t","𝘁")
jack = jack:gsub("T","𝗧")
jack = jack:gsub("u","𝘂")
jack = jack:gsub("U","𝗨")
jack = jack:gsub("v","𝘃")
jack = jack:gsub("V","𝗩")
jack = jack:gsub("w","𝘄")
jack = jack:gsub("W","𝗪")
jack = jack:gsub("x","𝘅")
jack = jack:gsub("X","𝗫")
jack = jack:gsub("y","𝘆")
jack = jack:gsub("Y","𝗬")
jack = jack:gsub("z","𝘇")
jack = jack:gsub("Z","𝗭")



local jack2 = Text:gsub('ض','ضَٰـُـٰٓ')
jack2 = jack2:gsub('ص','صَٰـُـٰٓ')
jack2 = jack2:gsub('ث','ثَٰـُـٰٓ')
jack2 = jack2:gsub('ق','قَٰـُـٰٓ')
jack2 = jack2:gsub('ف','فَٰ͒ـُـٰٓ')
jack2 = jack2:gsub('غ','غَٰـُـٰٓ')
jack2 = jack2:gsub('ع','عَٰـُـٰٓ')
jack2 = jack2:gsub('خ','خَٰ̐ـُـٰٓ')
jack2 = jack2:gsub('ح','حَٰـُـٰٓ')
jack2 = jack2:gsub('ج','جَٰـُـٰٓ')
jack2 = jack2:gsub('ش','شَٰـُـٰٓ')
jack2 = jack2:gsub('س','سَٰـُـٰٓ')
jack2 = jack2:gsub('ي','يَٰـُـٰٓ')
jack2 = jack2:gsub('ب','بَٰـُـٰٓ')
jack2 = jack2:gsub('ل','لَٰـُـٰٓ')
jack2 = jack2:gsub('ا','آ')
jack2 = jack2:gsub('ت','تَٰـُـٰٓ')
jack2 = jack2:gsub('ن','نَٰـُـٰٓ')
jack2 = jack2:gsub('م','مَٰـُـٰٓ')
jack2 = jack2:gsub('ك','ڪَٰـُـٰٓ')
jack2 = jack2:gsub('ط','طَٰـُـٰٓ')
jack2 = jack2:gsub('ظ','ظَٰـُـٰٓ')
jack2 = jack2:gsub('ء','ء')
jack2 = jack2:gsub('ؤ','ؤ')
jack2 = jack2:gsub('ر','ر')
jack2 = jack2:gsub('ى','ى')
jack2 = jack2:gsub('ز','ز')
jack2 = jack2:gsub('و','ﯛ̲୭')
jack2 = jack2:gsub("ه", "ۿۿہ")
jack2 = jack2:gsub('a',"𝖆")
jack2 = jack2:gsub('A',"𝖆")
jack2 = jack2:gsub("b","𝖇")
jack2 = jack2:gsub("B","𝖇")
jack2 = jack2:gsub("c","𝖈")
jack2 = jack2:gsub("C","𝖈")
jack2 = jack2:gsub("d","𝖉")
jack2 = jack2:gsub("D","𝖉")
jack2 = jack2:gsub("e","𝖊")
jack2 = jack2:gsub("E","𝖊")
jack2 = jack2:gsub("f","𝖋")
jack2 = jack2:gsub("F","𝖋")
jack2 = jack2:gsub("g","𝖌")
jack2 = jack2:gsub("G","𝖌")
jack2 = jack2:gsub("h","𝖍")
jack2 = jack2:gsub("H","𝖍")
jack2 = jack2:gsub("i","𝖎")
jack2 = jack2:gsub("I","𝖎")
jack2 = jack2:gsub("j","𝖏")
jack2 = jack2:gsub("J","𝖏")
jack2 = jack2:gsub("k","𝖐")
jack2 = jack2:gsub("K","𝖐")
jack2 = jack2:gsub("l","𝖑")
jack2 = jack2:gsub("L","𝖑")
jack2 = jack2:gsub("m","𝖒")
jack2 = jack2:gsub("M","𝖒")
jack2 = jack2:gsub("n","𝖓")
jack2 = jack2:gsub("N","𝖓")
jack2 = jack2:gsub("o","𝖔")
jack2 = jack2:gsub("O","𝖔")
jack2 = jack2:gsub("p","𝖕")
jack2 = jack2:gsub("P","𝖕")
jack2 = jack2:gsub("q","𝖖")
jack2 = jack2:gsub("Q","𝖖")
jack2 = jack2:gsub("r","𝖗")
jack2 = jack2:gsub("R","𝖗")
jack2 = jack2:gsub("s","𝖘")
jack2 = jack2:gsub("S","𝖘")
jack2 = jack2:gsub("t","𝖙")
jack2 = jack2:gsub("T","𝖙")
jack2 = jack2:gsub("u","𝖚")
jack2 = jack2:gsub("U","𝖚")
jack2 = jack2:gsub("v","𝖛")
jack2 = jack2:gsub("V","𝖛")
jack2 = jack2:gsub("w","𝖜")
jack2 = jack2:gsub("W","𝖜")
jack2 = jack2:gsub("x","𝖝")
jack2 = jack2:gsub("X","𝖝")
jack2 = jack2:gsub("y","𝖞")
jack2 = jack2:gsub("Y","𝖞")
jack2 = jack2:gsub("z","𝖟")
jack2 = jack2:gsub("Z","𝖟")


local jack3= Text:gsub('ض','ض')
jack3= jack3:gsub('ص','ص')
jack3= jack3:gsub('ث','ثہ')
jack3= jack3:gsub('ق','ق')
jack3= jack3:gsub('ف','فُہ')
jack3= jack3:gsub('غ','غہ')
jack3= jack3:gsub('ع','عہ')
jack3= jack3:gsub('ه','هٰہٰٖ')
jack3= jack3:gsub('خ','خہ')
jack3= jack3:gsub('ح','حہ')
jack3= jack3:gsub('ج','جہ')
jack3= jack3:gsub('د','د')
jack3= jack3:gsub('ذ','ذ')
jack3= jack3:gsub('ش','شہ')
jack3= jack3:gsub('س','سہ')
jack3= jack3:gsub('ي','يہ')
jack3= jack3:gsub('ب','بّ')
jack3= jack3:gsub('ل','لہ')
jack3= jack3:gsub('ا','ا')
jack3= jack3:gsub('ت','تہ')
jack3= jack3:gsub('ن','نٰہٰٖ')
jack3= jack3:gsub('م','مٰہٰٖ')
jack3= jack3:gsub('ك','كُہ')
jack3= jack3:gsub('ط','طہ')
jack3= jack3:gsub('ئ','ئ ْٰ')
jack3= jack3:gsub('ء','ء')
jack3= jack3:gsub('ؤ','ؤ')
jack3= jack3:gsub('ر','رَ')
jack3= jack3:gsub('لا','لہا')
jack3= jack3:gsub('ى','ىْ')
jack3= jack3:gsub('ة','ة')
jack3= jack3:gsub('و','و')
jack3= jack3:gsub('ز','ز')
jack3= jack3:gsub('ظ','ظۗہٰٰ')
jack3= jack3:gsub('q','𝐪')
jack3= jack3:gsub('Q','𝐪')
jack3= jack3:gsub('w','𝐰')
jack3= jack3:gsub('W','𝐰')
jack3= jack3:gsub('e','𝐞')
jack3= jack3:gsub('E','𝐞')
jack3= jack3:gsub('r','𝐫')
jack3= jack3:gsub('R','𝐫')
jack3= jack3:gsub('t','𝐭')
jack3= jack3:gsub('T','𝐭')
jack3= jack3:gsub('y','𝐲')
jack3= jack3:gsub('Y','𝐲')
jack3= jack3:gsub('u','𝐮')
jack3= jack3:gsub('i','𝐢')
jack3= jack3:gsub('o','𝐨')
jack3= jack3:gsub('p','𝐩')
jack3= jack3:gsub('a','𝐚')
jack3= jack3:gsub('s','𝐬')
jack3= jack3:gsub('d','𝐝')
jack3= jack3:gsub('f','𝐟')
jack3= jack3:gsub('g','𝐠')
jack3= jack3:gsub('h','𝐡')
jack3= jack3:gsub('j','𝐣')
jack3= jack3:gsub('k','𝐤')
jack3= jack3:gsub('U','𝐮')
jack3= jack3:gsub('I','𝐢')
jack3= jack3:gsub('O','𝐨')
jack3= jack3:gsub('P','𝐩')
jack3= jack3:gsub('A','𝐚')
jack3= jack3:gsub('S','𝐬')
jack3= jack3:gsub('D','𝐝')
jack3= jack3:gsub('F','𝐟')
jack3= jack3:gsub('G','𝐠')
jack3= jack3:gsub('H','𝐡')
jack3= jack3:gsub('J','𝐣')
jack3= jack3:gsub('K','𝐤')
jack3= jack3:gsub('L','𝐥')
jack3= jack3:gsub('l','𝐥')
jack3= jack3:gsub('z','𝐳')
jack3= jack3:gsub('Z','𝐳')
jack3= jack3:gsub('x','𝐱')
jack3= jack3:gsub('X','ẋ')
jack3= jack3:gsub('c','𝐜')
jack3= jack3:gsub('C','𝐜')
jack3= jack3:gsub('v','𝐯')
jack3= jack3:gsub('V','𝐯')
jack3= jack3:gsub('b','𝐛')
jack3= jack3:gsub('B','𝐛')
jack3= jack3:gsub('n','𝐧')
jack3= jack3:gsub('N','𝐧')
jack3= jack3:gsub('m','𝐦')
jack3= jack3:gsub('M','𝐦')


local jack4= Text:gsub('ض','ضۜہٰٰ')
jack4= jack4:gsub('ص','ضۜہٰٰ')
jack4= jack4:gsub('ث','ثہٰٰ')
jack4= jack4:gsub('ق','قྀ̲ہٰٰ')
jack4= jack4:gsub('ف','ف͒ہٰٰ')
jack4= jack4:gsub('غ','غہٰٰ')
jack4= jack4:gsub('ع','عہٰٰ')
jack4= jack4:gsub('ه','هٰہٰٖ')
jack4= jack4:gsub('خ','خٰ̐ہ ')
jack4= jack4:gsub('ح','حہٰٰ')
jack4= jack4:gsub('ج','جـٰ̲ـہْۧ')
jack4= jack4:gsub('د','دٰ')
jack4= jack4:gsub('ذ','ذِٰ')
jack4= jack4:gsub('ش','شِٰہٰٰ')
jack4= jack4:gsub('س','سٰٓ')
jack4= jack4:gsub('ي','يِٰہ')
jack4= jack4:gsub('ب','بّہ')
jack4= jack4:gsub('ل','لـٰ̲ـہ')
jack4= jack4:gsub('ا','آ')
jack4= jack4:gsub('ت','تَہَٰ')
jack4= jack4:gsub('ن','نَِہ')
jack4= jack4:gsub('م','مٰ̲ہ')
jack4= jack4:gsub('ك','ڪٰྀہٰٰ')
jack4= jack4:gsub('ط','طۨہٰٰ')
jack4= jack4:gsub('ئ','ئ ْٰ')
jack4= jack4:gsub('ء','ء')
jack4= jack4:gsub('ؤ','ؤ')
jack4= jack4:gsub('ر','رَ')
jack4= jack4:gsub('لا','لہا')
jack4= jack4:gsub('ى','ىْ')
jack4= jack4:gsub('ة','ة')
jack4= jack4:gsub('و','وِٰ')
jack4= jack4:gsub('ز','زَٰ')
jack4= jack4:gsub('ظ','ظۗہٰٰ')
jack4= jack4:gsub('q','𝑸')
jack4= jack4:gsub('Q','𝑸')
jack4= jack4:gsub('w','𝑾')
jack4= jack4:gsub('W','𝑾')
jack4= jack4:gsub('e','𝑬')
jack4= jack4:gsub('E','𝑬')
jack4= jack4:gsub('r','𝑹')
jack4= jack4:gsub('R','𝑹')
jack4= jack4:gsub('t','𝑻')
jack4= jack4:gsub('T','𝑻')
jack4= jack4:gsub('y','𝒀')
jack4= jack4:gsub('Y','𝒀')
jack4= jack4:gsub('u','𝑼')
jack4= jack4:gsub('U','𝑼')
jack4= jack4:gsub('i','𝑰')
jack4= jack4:gsub('I','𝑰')
jack4= jack4:gsub('o','𝑶')
jack4= jack4:gsub('O','𝑶')
jack4= jack4:gsub('p','𝑷')
jack4= jack4:gsub('P','𝑷')
jack4= jack4:gsub('a','𝑨')
jack4= jack4:gsub('A','𝑨')
jack4= jack4:gsub('s','𝑺')
jack4= jack4:gsub('S','𝑺')
jack4= jack4:gsub('d','𝑫')
jack4= jack4:gsub('D','𝑫')
jack4= jack4:gsub('f','𝑭')
jack4= jack4:gsub('F','𝑭')
jack4= jack4:gsub('g','𝑮')
jack4= jack4:gsub('G','𝑮')
jack4= jack4:gsub('h','𝑯')
jack4= jack4:gsub('H','𝑯')
jack4= jack4:gsub('j','𝑱')
jack4= jack4:gsub('J','𝑱')
jack4= jack4:gsub('k','𝑲')
jack4= jack4:gsub('K','𝑲')
jack4= jack4:gsub('l','𝑳')
jack4= jack4:gsub('L','𝑳')
jack4= jack4:gsub('z','𝒁')
jack4= jack4:gsub('Z','𝒁')
jack4= jack4:gsub('x','𝑿')
jack4= jack4:gsub('X','𝑿')
jack4= jack4:gsub('c','𝑪')
jack4= jack4:gsub('C','𝑪')
jack4= jack4:gsub('v','𝑽')
jack4= jack4:gsub('V','𝑽')
jack4= jack4:gsub('b','𝑩')
jack4= jack4:gsub('B','𝑩')
jack4= jack4:gsub('n','𝑵')
jack4= jack4:gsub('N','𝑵')
jack4= jack4:gsub('m','𝑴')
jack4= jack4:gsub('M','𝑴')



local jack5= Text:gsub('ض','ضَ')
jack5= jack5:gsub('ص','صً')
jack5= jack5:gsub('ث','ثَ')
jack5= jack5:gsub('ق','قُ')
jack5= jack5:gsub('ف','فّ')
jack5= jack5:gsub('غ','غِ')
jack5= jack5:gsub('ع','عُ')
jack5= jack5:gsub('ه','ﮭ')
jack5= jack5:gsub('خ','خِ')
jack5= jack5:gsub('ح','حٌ')
jack5= jack5:gsub('ج','جُ')
jack5= jack5:gsub('د','دِ')
jack5= jack5:gsub('ذ','ذَ')
jack5= jack5:gsub('ش','شِ')
jack5= jack5:gsub('س','سً')
jack5= jack5:gsub('ي','يْ')
jack5= jack5:gsub('ب','بّ')
jack5= jack5:gsub('ل','لَ')
jack5= jack5:gsub('ا','أُ')
jack5= jack5:gsub('ت','تٌ')
jack5= jack5:gsub('ن','نً')
jack5= jack5:gsub('م','مِ')
jack5= jack5:gsub('ك','ڳّ')
jack5= jack5:gsub('ط','طٌ')
jack5= jack5:gsub('ئ','ئ')
jack5= jack5:gsub('ء','ء')
jack5= jack5:gsub('ؤ','ؤ')
jack5= jack5:gsub('ر','رٌ')
jack5= jack5:gsub('لا','لٌأً')
jack5= jack5:gsub('ى','ى')
jack5= jack5:gsub('ة','ةَ')
jack5= jack5:gsub('و','وِ')
jack5= jack5:gsub('ز','زُ')
jack5= jack5:gsub('ظ','ظ')
jack5= jack5:gsub('q','𝒒')
jack5= jack5:gsub('Q','𝒒')
jack5= jack5:gsub('w','𝒘')
jack5= jack5:gsub('W','𝒘')
jack5= jack5:gsub('e','𝒆')
jack5= jack5:gsub('E','𝒆')
jack5= jack5:gsub('r','𝒓')
jack5= jack5:gsub('R','𝒓')
jack5= jack5:gsub('t','𝒕')
jack5= jack5:gsub('T','𝒕')
jack5= jack5:gsub('y','𝒚')
jack5= jack5:gsub('Y','𝒚')
jack5= jack5:gsub('u','𝒖')
jack5= jack5:gsub('U','𝒖')
jack5= jack5:gsub('i','𝒊')
jack5= jack5:gsub('I','𝒊')
jack5= jack5:gsub('o','𝒐')
jack5= jack5:gsub('O','𝒐')
jack5= jack5:gsub('p','𝒑')
jack5= jack5:gsub('P','𝒑')
jack5= jack5:gsub('a','𝒂')
jack5= jack5:gsub('A','𝒂')
jack5= jack5:gsub('s','𝒔')
jack5= jack5:gsub('S','𝒔')
jack5= jack5:gsub('d','𝒅')
jack5= jack5:gsub('D','𝒅')
jack5= jack5:gsub('f','𝒇')
jack5= jack5:gsub('F','𝒇')
jack5= jack5:gsub('g','𝒈')
jack5= jack5:gsub('G','𝒈')
jack5= jack5:gsub('h','𝒉')
jack5= jack5:gsub('H','𝒉')
jack5= jack5:gsub('j','𝒋')
jack5= jack5:gsub('J','𝒋')
jack5= jack5:gsub('K','𝒌')
jack5= jack5:gsub('k','𝒌')
jack5= jack5:gsub('L','𝒍')
jack5= jack5:gsub('l','𝒍')
jack5= jack5:gsub('z','𝒛')
jack5= jack5:gsub('Z','𝒛')
jack5= jack5:gsub('x','𝒙')
jack5= jack5:gsub('X','𝒙')
jack5= jack5:gsub('c','𝒄')
jack5= jack5:gsub('C','𝒄')
jack5= jack5:gsub('v','𝒗')
jack5= jack5:gsub('V','𝒗')
jack5= jack5:gsub('b','𝒃')
jack5= jack5:gsub('B','𝒃')
jack5= jack5:gsub('n','𝒏')
jack5= jack5:gsub('N','𝒏')
jack5= jack5:gsub('m','𝒎')
jack5= jack5:gsub('M','𝒎')



local jack6= Text:gsub('ض','ﺿ̭͠')
jack6= jack6:gsub('ص','ﺻ͡')
jack6= jack6:gsub('ث','ﺜ̲')
jack6= jack6:gsub('ق','ﭰ')
jack6= jack6:gsub('ف','ﻓ̲')
jack6= jack6:gsub('غ','ﻏ̲')
jack6= jack6:gsub('ع','ﻌ̲')
jack6= jack6:gsub('ه','ﮬ̲̌')
jack6= jack6:gsub('خ','خٌ')
jack6= jack6:gsub('ح','ﺣ̅')
jack6= jack6:gsub('ج','جُ')
jack6= jack6:gsub('د','ډ̝')
jack6= jack6:gsub('ذ','ذً')
jack6= jack6:gsub('ش','ﺷ̲')
jack6= jack6:gsub('س','ﺳ̉')
jack6= jack6:gsub('ي','ﯾ̃̐')
jack6= jack6:gsub('ب','ﺑ̲')
jack6= jack6:gsub('ل','ا̄ﻟ')
jack6= jack6:gsub('ا','ﺈ̃')
jack6= jack6:gsub('ت','ټُ')
jack6= jack6:gsub('ن','ﻧ̲')
jack6= jack6:gsub('م','ﻣ̲̉')
jack6= jack6:gsub('ك','گ')
jack6= jack6:gsub('ط','ﻁ̲')
jack6= jack6:gsub('ئ',' ْٰئ')
jack6= jack6:gsub('ء','ء')
jack6= jack6:gsub('ؤ','ؤ')
jack6= jack6:gsub('ر','ہڕ')
jack6= jack6:gsub('لا','ﻟ̲ﺂ̲')
jack6= jack6:gsub('ى','ى')
jack6= jack6:gsub('ة','ة')
jack6= jack6:gsub('و','ۇۈۉ')
jack6= jack6:gsub('ز','زُ')
jack6= jack6:gsub('ظ','ﻇ̲')
jack6= jack6:gsub('q','ǫ')
jack6= jack6:gsub('Q','ǫ')
jack6= jack6:gsub('w','ᴡ')
jack6= jack6:gsub('W','ᴡ')
jack6= jack6:gsub('e','ᴇ')
jack6= jack6:gsub('E','ᴇ')
jack6= jack6:gsub('r','ʀ')
jack6= jack6:gsub('R','ʀ')
jack6= jack6:gsub('t','ᴛ')
jack6= jack6:gsub('T','ᴛ')
jack6= jack6:gsub('y','ʏ')
jack6= jack6:gsub('Y','ʏ')
jack6= jack6:gsub('u','ụ')
jack6= jack6:gsub('U','ụ')
jack6= jack6:gsub('i','ɪ')
jack6= jack6:gsub('I','ɪ')
jack6= jack6:gsub('o','ᴏ')
jack6= jack6:gsub('O','ᴏ')
jack6= jack6:gsub('p','ᴘ')
jack6= jack6:gsub('P','ᴘ')
jack6= jack6:gsub('a','ᴀ')
jack6= jack6:gsub('A','ᴀ')
jack6= jack6:gsub('s','ѕ')
jack6= jack6:gsub('S','ѕ')
jack6= jack6:gsub('d','ᴅ')
jack6= jack6:gsub('D','ᴅ')
jack6= jack6:gsub('f','ғ')
jack6= jack6:gsub('F','ғ')
jack6= jack6:gsub('g','ɢ')
jack6= jack6:gsub('G','ɢ')
jack6= jack6:gsub('h','ʜ')
jack6= jack6:gsub('H','ʜ')
jack6= jack6:gsub('j','ᴊ')
jack6= jack6:gsub('J','ᴊ')
jack6= jack6:gsub('K','ᴋ')
jack6= jack6:gsub('k','ᴋ')
jack6= jack6:gsub('L','ʟ')
jack6= jack6:gsub('l','ʟ')
jack6= jack6:gsub('z','ᴢ')
jack6= jack6:gsub('Z','ᴢ')
jack6= jack6:gsub('x','х')
jack6= jack6:gsub('X','х')
jack6= jack6:gsub('c','ᴄ')
jack6= jack6:gsub('C','ᴄ')
jack6= jack6:gsub('v','ᴠ')
jack6= jack6:gsub('V','ᴠ')
jack6= jack6:gsub('b','ʙ')
jack6= jack6:gsub('B','ʙ')
jack6= jack6:gsub('n','ɴ')
jack6= jack6:gsub('N','ɴ')
jack6= jack6:gsub('m','ᴍ')
jack6= jack6:gsub('M','ᴍ')



local jack7= Text:gsub('ض','ﺿ')
jack7= jack7:gsub('ص','ﺻ')
jack7= jack7:gsub('ث','ﭥ')
jack7= jack7:gsub('ق','ﻗ̮ـ̃')
jack7= jack7:gsub('ف','ﭬ')
jack7= jack7:gsub('غ','ﻏ̣̐')
jack7= jack7:gsub('ع','ﻋ')
jack7= jack7:gsub('ه','ھَہّ')
jack7= jack7:gsub('خ','ﺧ')
jack7= jack7:gsub('ح','פ')
jack7= jack7:gsub('ج','ﭴ')
jack7= jack7:gsub('د','ﮃ')
jack7= jack7:gsub('ذ','ذ')
jack7= jack7:gsub('ش','ﺷ')
jack7= jack7:gsub('س','ﺳ')
jack7= jack7:gsub('ي','ﯾ')
jack7= jack7:gsub('ب','ﺑ')
jack7= jack7:gsub('ل','ﻟ')
jack7= jack7:gsub('ا','ﺂ')
jack7= jack7:gsub('ت','ﭠ')
jack7= jack7:gsub('ن','ﻧ')
jack7= jack7:gsub('م','ﻣ̝̚')
jack7= jack7:gsub('ك','گـ')
jack7= jack7:gsub('ط','ﻁْ')
jack7= jack7:gsub('ئ','ٰئـ')
jack7= jack7:gsub('ء','ء')
jack7= jack7:gsub('ؤ','ﯗ')
jack7= jack7:gsub('ر','ړُ')
jack7= jack7:gsub('لا','ﻟآ')
jack7= jack7:gsub('ى','ـﮯ')
jack7= jack7:gsub('ة','ة')
jack7= jack7:gsub('و','ۆ')
jack7= jack7:gsub('ز','ژ')
jack7= jack7:gsub('ظ','ﻅ')
jack7= jack7:gsub('q','𝘘')
jack7= jack7:gsub('Q','𝘘')
jack7= jack7:gsub('w','𝘞')
jack7= jack7:gsub('W','𝘞')
jack7= jack7:gsub('e','𝘌')
jack7= jack7:gsub('E','𝘌')
jack7= jack7:gsub('r','𝘙')
jack7= jack7:gsub('R','𝘙')
jack7= jack7:gsub('t','𝘛')
jack7= jack7:gsub('T','𝘛')
jack7= jack7:gsub('y','𝘠')
jack7= jack7:gsub('Y','𝘠')
jack7= jack7:gsub('u','𝘜')
jack7= jack7:gsub('U','𝘜')
jack7= jack7:gsub('i','𝘐')
jack7= jack7:gsub('I','𝘐')
jack7= jack7:gsub('o','𝘖')
jack7= jack7:gsub('O','𝘖')
jack7= jack7:gsub('p','𝘗')
jack7= jack7:gsub('P','𝘗')
jack7= jack7:gsub('a','𝘈')
jack7= jack7:gsub('A','𝘈')
jack7= jack7:gsub('s','𝘚')
jack7= jack7:gsub('S','𝘚')
jack7= jack7:gsub('d','𝘋')
jack7= jack7:gsub('D','𝘋')
jack7= jack7:gsub('f','𝘍')
jack7= jack7:gsub('F','𝘍')
jack7= jack7:gsub('g','𝘎')
jack7= jack7:gsub('G','𝘎')
jack7= jack7:gsub('h','𝘏')
jack7= jack7:gsub('H','𝘏')
jack7= jack7:gsub('j','𝘑')
jack7= jack7:gsub('J','𝘑')
jack7= jack7:gsub('k','𝘒')
jack7= jack7:gsub('K','𝘒')
jack7= jack7:gsub('L','𝘓')
jack7= jack7:gsub('l','𝘓')
jack7= jack7:gsub('z','𝘡')
jack7= jack7:gsub('Z','𝘡')
jack7= jack7:gsub('x','𝘟')
jack7= jack7:gsub('X','𝘟')
jack7= jack7:gsub('c','𝘊')
jack7= jack7:gsub('C','𝘊')
jack7= jack7:gsub('v','𝘝')
jack7= jack7:gsub('V','𝘝')
jack7= jack7:gsub('b','𝘉')
jack7= jack7:gsub('B','𝘉')
jack7= jack7:gsub('n','𝘕')
jack7= jack7:gsub('N','𝘕')
jack7= jack7:gsub('m','𝘔')
jack7= jack7:gsub('M','𝘔')



local jack8= Text:gsub('ض','ض');
jack8= jack8:gsub('ص','صہٰ')
jack8= jack8:gsub('ث','ثہٰـ')
jack8= jack8:gsub('ق','قہٰ')
jack8= jack8:gsub('ف','فہٰ')
jack8= jack8:gsub('غ','غـْ')
jack8= jack8:gsub('ع','ع')
jack8= jack8:gsub('ه','هٰہٰٖ')
jack8= jack8:gsub('خ','خخَـ')
jack8= jack8:gsub('ح','حہٰ')
jack8= jack8:gsub('ج','ججہٰ')
jack8= jack8:gsub('د','دَ')
jack8= jack8:gsub('ذ','ذّ')
jack8= jack8:gsub('ش','ششہٰ')
jack8= jack8:gsub('س','سہٰ')
jack8= jack8:gsub('ي','يٰ')
jack8= jack8:gsub('ب','بٰٰ')
jack8= jack8:gsub('ل','لہٰ')
jack8= jack8:gsub('ا','آ')
jack8= jack8:gsub('ت','تہٰ')
jack8= jack8:gsub('ن','نہٰ')
jack8= jack8:gsub('م','مہٰ')
jack8= jack8:gsub('ك','ككہٰ')
jack8= jack8:gsub('ط','طہٰ')
jack8= jack8:gsub('ئ',' ْئٰ')
jack8= jack8:gsub('ء','ء')
jack8= jack8:gsub('ؤ','ؤؤَ')
jack8= jack8:gsub('ر','رَ')
jack8= jack8:gsub('لا','لہٰا')
jack8= jack8:gsub('ى','ىہٰ')
jack8= jack8:gsub('ة','ة')
jack8= jack8:gsub('و','ہٰو')
jack8= jack8:gsub('ز','ز')
jack8= jack8:gsub('ظ','ظہٰ')
jack8= jack8:gsub('q','𝚀')
jack8= jack8:gsub('Q','𝚀')
jack8= jack8:gsub('w','𝚆')
jack8= jack8:gsub('W','𝚆')
jack8= jack8:gsub('e','𝙴')
jack8= jack8:gsub('E','𝙴')
jack8= jack8:gsub('r','𝚁')
jack8= jack8:gsub('R','𝚁')
jack8= jack8:gsub('t','𝚃')
jack8= jack8:gsub('T','𝚃')
jack8= jack8:gsub('y','𝚈')
jack8= jack8:gsub('Y','𝚈')
jack8= jack8:gsub('u','𝚄')
jack8= jack8:gsub('U','𝚄')
jack8= jack8:gsub('i','𝙸')
jack8= jack8:gsub('I','𝙸')
jack8= jack8:gsub('o','𝙾')
jack8= jack8:gsub('O','𝙾')
jack8= jack8:gsub('p','𝙿')
jack8= jack8:gsub('P','𝙿')
jack8= jack8:gsub('a','𝙰')
jack8= jack8:gsub('A','𝙰')
jack8= jack8:gsub('s','𝚂')
jack8= jack8:gsub('S','𝚂')
jack8= jack8:gsub('d','𝙳')
jack8= jack8:gsub('D','𝙳')
jack8= jack8:gsub('f','𝙵')
jack8= jack8:gsub('F','𝙵')
jack8= jack8:gsub('g','𝙶')
jack8= jack8:gsub('G','𝙶')
jack8= jack8:gsub('h','𝙷')
jack8= jack8:gsub('H','𝙷')
jack8= jack8:gsub('j','𝙹')
jack8= jack8:gsub('J','𝙹')
jack8= jack8:gsub('k','𝙺')
jack8= jack8:gsub('K','𝙺')
jack8= jack8:gsub('L','𝙻')
jack8= jack8:gsub('l','𝙻')
jack8= jack8:gsub('z','𝚉')
jack8= jack8:gsub('Z','𝚉')
jack8= jack8:gsub('x','𝚇')
jack8= jack8:gsub('X','𝚇')
jack8= jack8:gsub('c','𝙲')
jack8= jack8:gsub('C','𝙲')
jack8= jack8:gsub('v','𝚅')
jack8= jack8:gsub('V','𝚅')
jack8= jack8:gsub('b','𝙱')
jack8= jack8:gsub('B','𝙱')
jack8= jack8:gsub('n','𝙽')
jack8= jack8:gsub('N','𝙽')
jack8= jack8:gsub('m','𝙼')
jack8= jack8:gsub('M','𝙼')



local jack9= Text:gsub('ض','ض')
jack9= jack9:gsub('ص','ص')
jack9= jack9:gsub('ث','ث')
jack9= jack9:gsub('ق','قٌ')
jack9= jack9:gsub('ف','فُ')
jack9= jack9:gsub('غ','غ')
jack9= jack9:gsub('ع','عٍ')
jack9= jack9:gsub('ه','هـ')
jack9= jack9:gsub('خ','خـ')
jack9= jack9:gsub('ح','حٍ')
jack9= jack9:gsub('ج','جٍ')
jack9= jack9:gsub('د','دِ')
jack9= jack9:gsub('ذ','ذَ')
jack9= jack9:gsub('ش','شُ')
jack9= jack9:gsub('س','س')
jack9= jack9:gsub('ي','ي')
jack9= jack9:gsub('ب','بَ')
jack9= jack9:gsub('ل','لُِ')
jack9= jack9:gsub('ا','آ')
jack9= jack9:gsub('ت','ت')
jack9= jack9:gsub('ن','ن')
jack9= jack9:gsub('م','م')
jack9= jack9:gsub('ك','ڪ')
jack9= jack9:gsub('ط','طُ')
jack9= jack9:gsub('ئ','ئ ْٰ')
jack9= jack9:gsub('ء','ء')
jack9= jack9:gsub('ؤ','ؤ')
jack9= jack9:gsub('ر','ر')
jack9= jack9:gsub('لا','لُِآ')
jack9= jack9:gsub('ى','ىْ')
jack9= jack9:gsub('ة','ة')
jack9= jack9:gsub('و','وو')
jack9= jack9:gsub('ز','ز')
jack9= jack9:gsub('ظ','ظهُ')
jack9= jack9:gsub('q','ℚ')
jack9= jack9:gsub('Q','ℚ')
jack9= jack9:gsub('w','𝕎')
jack9= jack9:gsub('W','𝕎')
jack9= jack9:gsub('e','𝔼')
jack9= jack9:gsub('E','𝔼')
jack9= jack9:gsub('r','ℝ')
jack9= jack9:gsub('R','ℝ')
jack9= jack9:gsub('t','𝕋')
jack9= jack9:gsub('T','𝕋')
jack9= jack9:gsub('y','𝕐')
jack9= jack9:gsub('Y','𝕐')
jack9= jack9:gsub('u','𝕌')
jack9= jack9:gsub('U','𝕌')
jack9= jack9:gsub('i','𝕀')
jack9= jack9:gsub('I','𝕀')
jack9= jack9:gsub('o','𝕆')
jack9= jack9:gsub('O','𝕆')
jack9= jack9:gsub('p','ℙ')
jack9= jack9:gsub('P','ℙ')
jack9= jack9:gsub('a','𝔸')
jack9= jack9:gsub('A','𝔸')
jack9= jack9:gsub('s','𝕊')
jack9= jack9:gsub('S','𝕊')
jack9= jack9:gsub('d','𝔻')
jack9= jack9:gsub('D','𝔻')
jack9= jack9:gsub('f','𝔽')
jack9= jack9:gsub('F','𝔽')
jack9= jack9:gsub('g','𝔾')
jack9= jack9:gsub('G','𝔾')
jack9= jack9:gsub('h','ℍ')
jack9= jack9:gsub('H','ℍ')
jack9= jack9:gsub('j','𝕁')
jack9= jack9:gsub('J','𝕁')
jack9= jack9:gsub('k','𝕂')
jack9= jack9:gsub('K','𝕂')
jack9= jack9:gsub('L','𝕃')
jack9= jack9:gsub('l','𝕃')
jack9= jack9:gsub('z','ℤ')
jack9= jack9:gsub('Z','ℤ')
jack9= jack9:gsub('x','𝕏')
jack9= jack9:gsub('X','𝕏')
jack9= jack9:gsub('c','ℂ')
jack9= jack9:gsub('C','ℂ')
jack9= jack9:gsub('v','𝕍')
jack9= jack9:gsub('V','𝕍')
jack9= jack9:gsub('b','𝔹')
jack9= jack9:gsub('B','𝔹')
jack9= jack9:gsub('n','ℕ')
jack9= jack9:gsub('N','ℕ')
jack9= jack9:gsub('m','𝕄')
jack9= jack9:gsub('M','𝕄')


local Text_jacka = "1- `"..jack..EmojeS[math.random(#EmojeS)]
.."`\n\n2- `"..jack2..EmojeS[math.random(#EmojeS)]
.."`\n\n3- `"..jack3..EmojeS[math.random(#EmojeS)]
.."`\n\n4- `"..jack4..EmojeS[math.random(#EmojeS)]
.."`\n\n5- `"..jack5..EmojeS[math.random(#EmojeS)]
.."`\n\n6- `"..jack6..EmojeS[math.random(#EmojeS)]
.."`\n\n7- `"..jack7..EmojeS[math.random(#EmojeS)]
.."`\n\n8- `"..jack8..Emoje[math.random(#Emoje)]
.."`\n\n9- `"..jack9..Emoje[math.random(#Emoje)]
.."`\n\n10- `"..jack5..Emoje[math.random(#Emoje)]
Text_jacka = Text_jacka.."`\n\n اضغط علـي الاسـم ليـتم النـسخ \n★"
sendMsg(msg.chat_id_,msg.id_,Text_jacka)
return false
end
end

end
local function TextRes(msg)

if msg.text and msg.type ~= "pv" and redis:get(debo..":jackNow:"..msg.sender_user_id_) then
Text = msg.text
redis:del(debo..":jackNow:"..msg.sender_user_id_)
if utf8.len(msg.text) > 300 then
sendMsg(msg.chat_id_,msg.id_," لا يمكنك زخرفه اكثر من 300 حرف \n  ارسل امر زخرفه وحاول مجددا بحروف اقل")    
return false
end
local EmojeS = {
' 𓁻',
' 𓏴  ',
' 𓏶 ',
' 𓏡',
' 𓏢', 
' 𓏣', 
' ☽‘',
' 𖠱²²', 
'▽', 
' 𖡛“', 
' 𖡚℡', 
' 𖡨', 
}

local Emoje = {
' ♕',
' 𖤍',
'˛𖤓',
' ཻ ☫',
' ♫ ',
' 𖠶 ',
' 𖠲',
' 𖡥',
'  ☬',
' 𖤐',
' 𓇼',
' ♘  '
}


local jack = Text:gsub('ض','ضِٰـِۢ')
jack = jack:gsub('ص','صِٰـِۢ')
jack = jack:gsub('ث','ثِٰـِۢ')
jack = jack:gsub('ق','قِٰـِۢ')
jack = jack:gsub('ف','فِٰ͒ـِۢ')
jack = jack:gsub('غ','غِٰـِۢ')
jack = jack:gsub('ع','عِٰـِۢ')
jack = jack:gsub('خ','خِٰ̐ـِۢ')
jack = jack:gsub('ح','حِٰـِۢ')
jack = jack:gsub('ج','جِٰـِۢ')
jack = jack:gsub('ش','شِٰـِۢ')
jack = jack:gsub('س','سِٰـِۢ')
jack = jack:gsub('ي','يِٰـِۢ')
jack = jack:gsub('ب','بِٰـِۢ')
jack = jack:gsub('ل','لِٰـِۢ')
jack = jack:gsub('ا','آ')
jack = jack:gsub('ت','تِٰـِۢ')
jack = jack:gsub('ن','نِٰـِۢ')
jack = jack:gsub('م','مِٰـِۢ')
jack = jack:gsub('ك','ڪِٰـِۢ')
jack = jack:gsub('ط','طِٰـِۢ')
jack = jack:gsub('ظ','ظِٰـِۢ')
jack = jack:gsub('ء','ء')
jack = jack:gsub('ؤ','ؤ')
jack = jack:gsub('ر','ر')
jack = jack:gsub('ى','ى')
jack = jack:gsub('ز','ز')
jack = jack:gsub('و','ﯛ̲୭')
jack = jack:gsub('ه','ۿۿہ')
jack = jack:gsub('a','𝗮')
jack = jack:gsub('A','𝗔')
jack = jack:gsub("b","𝗯")
jack = jack:gsub("B","𝗕")
jack = jack:gsub("c","𝗰")
jack = jack:gsub("C","𝗖")
jack = jack:gsub("d","𝗱")
jack = jack:gsub("D","𝗗")
jack = jack:gsub("e","𝗲")
jack = jack:gsub("E","𝗘")
jack = jack:gsub("f","𝗳")
jack = jack:gsub("F","𝗙")
jack = jack:gsub("g","𝗴")
jack = jack:gsub("G","𝗚")
jack = jack:gsub("h","𝗵")
jack = jack:gsub("H","𝗛")
jack = jack:gsub("i","𝗹")
jack = jack:gsub("I","𝗜")
jack = jack:gsub("j","𝗝")
jack = jack:gsub("J","𝗝")
jack = jack:gsub("k","𝗸")
jack = jack:gsub("K","𝗞")
jack = jack:gsub("l","𝗹")
jack = jack:gsub("L","𝗟")
jack = jack:gsub("m","𝗺")
jack = jack:gsub("M","𝗠")
jack = jack:gsub("n","𝗻")
jack = jack:gsub("N","𝗡")
jack = jack:gsub("o","𝗼")
jack = jack:gsub("O","𝗢")
jack = jack:gsub("p","𝗽")
jack = jack:gsub("P","𝗣")
jack = jack:gsub("q","𝗾")
jack = jack:gsub("Q","𝗤")
jack = jack:gsub("r","𝗿")
jack = jack:gsub("R","𝗥")
jack = jack:gsub("s","𝘀")
jack = jack:gsub("S","𝗦")
jack = jack:gsub("t","𝘁")
jack = jack:gsub("T","𝗧")
jack = jack:gsub("u","𝘂")
jack = jack:gsub("U","𝗨")
jack = jack:gsub("v","𝘃")
jack = jack:gsub("V","𝗩")
jack = jack:gsub("w","𝘄")
jack = jack:gsub("W","𝗪")
jack = jack:gsub("x","𝘅")
jack = jack:gsub("X","𝗫")
jack = jack:gsub("y","𝘆")
jack = jack:gsub("Y","𝗬")
jack = jack:gsub("z","𝘇")
jack = jack:gsub("Z","𝗭")



local jack2 = Text:gsub('ض','ضَٰـُـٰٓ')
jack2 = jack2:gsub('ص','صَٰـُـٰٓ')
jack2 = jack2:gsub('ث','ثَٰـُـٰٓ')
jack2 = jack2:gsub('ق','قَٰـُـٰٓ')
jack2 = jack2:gsub('ف','فَٰ͒ـُـٰٓ')
jack2 = jack2:gsub('غ','غَٰـُـٰٓ')
jack2 = jack2:gsub('ع','عَٰـُـٰٓ')
jack2 = jack2:gsub('خ','خَٰ̐ـُـٰٓ')
jack2 = jack2:gsub('ح','حَٰـُـٰٓ')
jack2 = jack2:gsub('ج','جَٰـُـٰٓ')
jack2 = jack2:gsub('ش','شَٰـُـٰٓ')
jack2 = jack2:gsub('س','سَٰـُـٰٓ')
jack2 = jack2:gsub('ي','يَٰـُـٰٓ')
jack2 = jack2:gsub('ب','بَٰـُـٰٓ')
jack2 = jack2:gsub('ل','لَٰـُـٰٓ')
jack2 = jack2:gsub('ا','آ')
jack2 = jack2:gsub('ت','تَٰـُـٰٓ')
jack2 = jack2:gsub('ن','نَٰـُـٰٓ')
jack2 = jack2:gsub('م','مَٰـُـٰٓ')
jack2 = jack2:gsub('ك','ڪَٰـُـٰٓ')
jack2 = jack2:gsub('ط','طَٰـُـٰٓ')
jack2 = jack2:gsub('ظ','ظَٰـُـٰٓ')
jack2 = jack2:gsub('ء','ء')
jack2 = jack2:gsub('ؤ','ؤ')
jack2 = jack2:gsub('ر','ر')
jack2 = jack2:gsub('ى','ى')
jack2 = jack2:gsub('ز','ز')
jack2 = jack2:gsub('و','ﯛ̲୭')
jack2 = jack2:gsub("ه", "ۿۿہ")
jack2 = jack2:gsub('a',"𝖆")
jack2 = jack2:gsub('A',"𝖆")
jack2 = jack2:gsub("b","𝖇")
jack2 = jack2:gsub("B","𝖇")
jack2 = jack2:gsub("c","𝖈")
jack2 = jack2:gsub("C","𝖈")
jack2 = jack2:gsub("d","𝖉")
jack2 = jack2:gsub("D","𝖉")
jack2 = jack2:gsub("e","𝖊")
jack2 = jack2:gsub("E","𝖊")
jack2 = jack2:gsub("f","𝖋")
jack2 = jack2:gsub("F","𝖋")
jack2 = jack2:gsub("g","𝖌")
jack2 = jack2:gsub("G","𝖌")
jack2 = jack2:gsub("h","𝖍")
jack2 = jack2:gsub("H","𝖍")
jack2 = jack2:gsub("i","𝖎")
jack2 = jack2:gsub("I","𝖎")
jack2 = jack2:gsub("j","𝖏")
jack2 = jack2:gsub("J","𝖏")
jack2 = jack2:gsub("k","𝖐")
jack2 = jack2:gsub("K","𝖐")
jack2 = jack2:gsub("l","𝖑")
jack2 = jack2:gsub("L","𝖑")
jack2 = jack2:gsub("m","𝖒")
jack2 = jack2:gsub("M","𝖒")
jack2 = jack2:gsub("n","𝖓")
jack2 = jack2:gsub("N","𝖓")
jack2 = jack2:gsub("o","𝖔")
jack2 = jack2:gsub("O","𝖔")
jack2 = jack2:gsub("p","𝖕")
jack2 = jack2:gsub("P","𝖕")
jack2 = jack2:gsub("q","𝖖")
jack2 = jack2:gsub("Q","𝖖")
jack2 = jack2:gsub("r","𝖗")
jack2 = jack2:gsub("R","𝖗")
jack2 = jack2:gsub("s","𝖘")
jack2 = jack2:gsub("S","𝖘")
jack2 = jack2:gsub("t","𝖙")
jack2 = jack2:gsub("T","𝖙")
jack2 = jack2:gsub("u","𝖚")
jack2 = jack2:gsub("U","𝖚")
jack2 = jack2:gsub("v","𝖛")
jack2 = jack2:gsub("V","𝖛")
jack2 = jack2:gsub("w","𝖜")
jack2 = jack2:gsub("W","𝖜")
jack2 = jack2:gsub("x","𝖝")
jack2 = jack2:gsub("X","𝖝")
jack2 = jack2:gsub("y","𝖞")
jack2 = jack2:gsub("Y","𝖞")
jack2 = jack2:gsub("z","𝖟")
jack2 = jack2:gsub("Z","𝖟")


local jack3= Text:gsub('ض','ض')
jack3= jack3:gsub('ص','ص')
jack3= jack3:gsub('ث','ثہ')
jack3= jack3:gsub('ق','ق')
jack3= jack3:gsub('ف','فُہ')
jack3= jack3:gsub('غ','غہ')
jack3= jack3:gsub('ع','عہ')
jack3= jack3:gsub('ه','هٰہٰٖ')
jack3= jack3:gsub('خ','خہ')
jack3= jack3:gsub('ح','حہ')
jack3= jack3:gsub('ج','جہ')
jack3= jack3:gsub('د','د')
jack3= jack3:gsub('ذ','ذ')
jack3= jack3:gsub('ش','شہ')
jack3= jack3:gsub('س','سہ')
jack3= jack3:gsub('ي','يہ')
jack3= jack3:gsub('ب','بّ')
jack3= jack3:gsub('ل','لہ')
jack3= jack3:gsub('ا','ا')
jack3= jack3:gsub('ت','تہ')
jack3= jack3:gsub('ن','نٰہٰٖ')
jack3= jack3:gsub('م','مٰہٰٖ')
jack3= jack3:gsub('ك','كُہ')
jack3= jack3:gsub('ط','طہ')
jack3= jack3:gsub('ئ','ئ ْٰ')
jack3= jack3:gsub('ء','ء')
jack3= jack3:gsub('ؤ','ؤ')
jack3= jack3:gsub('ر','رَ')
jack3= jack3:gsub('لا','لہا')
jack3= jack3:gsub('ى','ىْ')
jack3= jack3:gsub('ة','ة')
jack3= jack3:gsub('و','و')
jack3= jack3:gsub('ز','ز')
jack3= jack3:gsub('ظ','ظۗہٰٰ')
jack3= jack3:gsub('q','𝐪')
jack3= jack3:gsub('Q','𝐪')
jack3= jack3:gsub('w','𝐰')
jack3= jack3:gsub('W','𝐰')
jack3= jack3:gsub('e','𝐞')
jack3= jack3:gsub('E','𝐞')
jack3= jack3:gsub('r','𝐫')
jack3= jack3:gsub('R','𝐫')
jack3= jack3:gsub('t','𝐭')
jack3= jack3:gsub('T','𝐭')
jack3= jack3:gsub('y','𝐲')
jack3= jack3:gsub('Y','𝐲')
jack3= jack3:gsub('u','𝐮')
jack3= jack3:gsub('i','𝐢')
jack3= jack3:gsub('o','𝐨')
jack3= jack3:gsub('p','𝐩')
jack3= jack3:gsub('a','𝐚')
jack3= jack3:gsub('s','𝐬')
jack3= jack3:gsub('d','𝐝')
jack3= jack3:gsub('f','𝐟')
jack3= jack3:gsub('g','𝐠')
jack3= jack3:gsub('h','𝐡')
jack3= jack3:gsub('j','𝐣')
jack3= jack3:gsub('k','𝐤')
jack3= jack3:gsub('U','𝐮')
jack3= jack3:gsub('I','𝐢')
jack3= jack3:gsub('O','𝐨')
jack3= jack3:gsub('P','𝐩')
jack3= jack3:gsub('A','𝐚')
jack3= jack3:gsub('S','𝐬')
jack3= jack3:gsub('D','𝐝')
jack3= jack3:gsub('F','𝐟')
jack3= jack3:gsub('G','𝐠')
jack3= jack3:gsub('H','𝐡')
jack3= jack3:gsub('J','𝐣')
jack3= jack3:gsub('K','𝐤')
jack3= jack3:gsub('L','𝐥')
jack3= jack3:gsub('l','𝐥')
jack3= jack3:gsub('z','𝐳')
jack3= jack3:gsub('Z','𝐳')
jack3= jack3:gsub('x','𝐱')
jack3= jack3:gsub('X','ẋ')
jack3= jack3:gsub('c','𝐜')
jack3= jack3:gsub('C','𝐜')
jack3= jack3:gsub('v','𝐯')
jack3= jack3:gsub('V','𝐯')
jack3= jack3:gsub('b','𝐛')
jack3= jack3:gsub('B','𝐛')
jack3= jack3:gsub('n','𝐧')
jack3= jack3:gsub('N','𝐧')
jack3= jack3:gsub('m','𝐦')
jack3= jack3:gsub('M','𝐦')


local jack4= Text:gsub('ض','ضۜہٰٰ')
jack4= jack4:gsub('ص','ضۜہٰٰ')
jack4= jack4:gsub('ث','ثہٰٰ')
jack4= jack4:gsub('ق','قྀ̲ہٰٰ')
jack4= jack4:gsub('ف','ف͒ہٰٰ')
jack4= jack4:gsub('غ','غہٰٰ')
jack4= jack4:gsub('ع','عہٰٰ')
jack4= jack4:gsub('ه','هٰہٰٖ')
jack4= jack4:gsub('خ','خٰ̐ہ ')
jack4= jack4:gsub('ح','حہٰٰ')
jack4= jack4:gsub('ج','جـٰ̲ـہْۧ')
jack4= jack4:gsub('د','دٰ')
jack4= jack4:gsub('ذ','ذِٰ')
jack4= jack4:gsub('ش','شِٰہٰٰ')
jack4= jack4:gsub('س','سٰٓ')
jack4= jack4:gsub('ي','يِٰہ')
jack4= jack4:gsub('ب','بّہ')
jack4= jack4:gsub('ل','لـٰ̲ـہ')
jack4= jack4:gsub('ا','آ')
jack4= jack4:gsub('ت','تَہَٰ')
jack4= jack4:gsub('ن','نَِہ')
jack4= jack4:gsub('م','مٰ̲ہ')
jack4= jack4:gsub('ك','ڪٰྀہٰٰ')
jack4= jack4:gsub('ط','طۨہٰٰ')
jack4= jack4:gsub('ئ','ئ ْٰ')
jack4= jack4:gsub('ء','ء')
jack4= jack4:gsub('ؤ','ؤ')
jack4= jack4:gsub('ر','رَ')
jack4= jack4:gsub('لا','لہا')
jack4= jack4:gsub('ى','ىْ')
jack4= jack4:gsub('ة','ة')
jack4= jack4:gsub('و','وِٰ')
jack4= jack4:gsub('ز','زَٰ')
jack4= jack4:gsub('ظ','ظۗہٰٰ')
jack4= jack4:gsub('q','𝑸')
jack4= jack4:gsub('Q','𝑸')
jack4= jack4:gsub('w','𝑾')
jack4= jack4:gsub('W','𝑾')
jack4= jack4:gsub('e','𝑬')
jack4= jack4:gsub('E','𝑬')
jack4= jack4:gsub('r','𝑹')
jack4= jack4:gsub('R','𝑹')
jack4= jack4:gsub('t','𝑻')
jack4= jack4:gsub('T','𝑻')
jack4= jack4:gsub('y','𝒀')
jack4= jack4:gsub('Y','𝒀')
jack4= jack4:gsub('u','𝑼')
jack4= jack4:gsub('U','𝑼')
jack4= jack4:gsub('i','𝑰')
jack4= jack4:gsub('I','𝑰')
jack4= jack4:gsub('o','𝑶')
jack4= jack4:gsub('O','𝑶')
jack4= jack4:gsub('p','𝑷')
jack4= jack4:gsub('P','𝑷')
jack4= jack4:gsub('a','𝑨')
jack4= jack4:gsub('A','𝑨')
jack4= jack4:gsub('s','𝑺')
jack4= jack4:gsub('S','𝑺')
jack4= jack4:gsub('d','𝑫')
jack4= jack4:gsub('D','𝑫')
jack4= jack4:gsub('f','𝑭')
jack4= jack4:gsub('F','𝑭')
jack4= jack4:gsub('g','𝑮')
jack4= jack4:gsub('G','𝑮')
jack4= jack4:gsub('h','𝑯')
jack4= jack4:gsub('H','𝑯')
jack4= jack4:gsub('j','𝑱')
jack4= jack4:gsub('J','𝑱')
jack4= jack4:gsub('k','𝑲')
jack4= jack4:gsub('K','𝑲')
jack4= jack4:gsub('l','𝑳')
jack4= jack4:gsub('L','𝑳')
jack4= jack4:gsub('z','𝒁')
jack4= jack4:gsub('Z','𝒁')
jack4= jack4:gsub('x','𝑿')
jack4= jack4:gsub('X','𝑿')
jack4= jack4:gsub('c','𝑪')
jack4= jack4:gsub('C','𝑪')
jack4= jack4:gsub('v','𝑽')
jack4= jack4:gsub('V','𝑽')
jack4= jack4:gsub('b','𝑩')
jack4= jack4:gsub('B','𝑩')
jack4= jack4:gsub('n','𝑵')
jack4= jack4:gsub('N','𝑵')
jack4= jack4:gsub('m','𝑴')
jack4= jack4:gsub('M','𝑴')



local jack5= Text:gsub('ض','ضَ')
jack5= jack5:gsub('ص','صً')
jack5= jack5:gsub('ث','ثَ')
jack5= jack5:gsub('ق','قُ')
jack5= jack5:gsub('ف','فّ')
jack5= jack5:gsub('غ','غِ')
jack5= jack5:gsub('ع','عُ')
jack5= jack5:gsub('ه','ﮭ')
jack5= jack5:gsub('خ','خِ')
jack5= jack5:gsub('ح','حٌ')
jack5= jack5:gsub('ج','جُ')
jack5= jack5:gsub('د','دِ')
jack5= jack5:gsub('ذ','ذَ')
jack5= jack5:gsub('ش','شِ')
jack5= jack5:gsub('س','سً')
jack5= jack5:gsub('ي','يْ')
jack5= jack5:gsub('ب','بّ')
jack5= jack5:gsub('ل','لَ')
jack5= jack5:gsub('ا','أُ')
jack5= jack5:gsub('ت','تٌ')
jack5= jack5:gsub('ن','نً')
jack5= jack5:gsub('م','مِ')
jack5= jack5:gsub('ك','ڳّ')
jack5= jack5:gsub('ط','طٌ')
jack5= jack5:gsub('ئ','ئ')
jack5= jack5:gsub('ء','ء')
jack5= jack5:gsub('ؤ','ؤ')
jack5= jack5:gsub('ر','رٌ')
jack5= jack5:gsub('لا','لٌأً')
jack5= jack5:gsub('ى','ى')
jack5= jack5:gsub('ة','ةَ')
jack5= jack5:gsub('و','وِ')
jack5= jack5:gsub('ز','زُ')
jack5= jack5:gsub('ظ','ظ')
jack5= jack5:gsub('q','𝒒')
jack5= jack5:gsub('Q','𝒒')
jack5= jack5:gsub('w','𝒘')
jack5= jack5:gsub('W','𝒘')
jack5= jack5:gsub('e','𝒆')
jack5= jack5:gsub('E','𝒆')
jack5= jack5:gsub('r','𝒓')
jack5= jack5:gsub('R','𝒓')
jack5= jack5:gsub('t','𝒕')
jack5= jack5:gsub('T','𝒕')
jack5= jack5:gsub('y','𝒚')
jack5= jack5:gsub('Y','𝒚')
jack5= jack5:gsub('u','𝒖')
jack5= jack5:gsub('U','𝒖')
jack5= jack5:gsub('i','𝒊')
jack5= jack5:gsub('I','𝒊')
jack5= jack5:gsub('o','𝒐')
jack5= jack5:gsub('O','𝒐')
jack5= jack5:gsub('p','𝒑')
jack5= jack5:gsub('P','𝒑')
jack5= jack5:gsub('a','𝒂')
jack5= jack5:gsub('A','𝒂')
jack5= jack5:gsub('s','𝒔')
jack5= jack5:gsub('S','𝒔')
jack5= jack5:gsub('d','𝒅')
jack5= jack5:gsub('D','𝒅')
jack5= jack5:gsub('f','𝒇')
jack5= jack5:gsub('F','𝒇')
jack5= jack5:gsub('g','𝒈')
jack5= jack5:gsub('G','𝒈')
jack5= jack5:gsub('h','𝒉')
jack5= jack5:gsub('H','𝒉')
jack5= jack5:gsub('j','𝒋')
jack5= jack5:gsub('J','𝒋')
jack5= jack5:gsub('K','𝒌')
jack5= jack5:gsub('k','𝒌')
jack5= jack5:gsub('L','𝒍')
jack5= jack5:gsub('l','𝒍')
jack5= jack5:gsub('z','𝒛')
jack5= jack5:gsub('Z','𝒛')
jack5= jack5:gsub('x','𝒙')
jack5= jack5:gsub('X','𝒙')
jack5= jack5:gsub('c','𝒄')
jack5= jack5:gsub('C','𝒄')
jack5= jack5:gsub('v','𝒗')
jack5= jack5:gsub('V','𝒗')
jack5= jack5:gsub('b','𝒃')
jack5= jack5:gsub('B','𝒃')
jack5= jack5:gsub('n','𝒏')
jack5= jack5:gsub('N','𝒏')
jack5= jack5:gsub('m','𝒎')
jack5= jack5:gsub('M','𝒎')



local jack6= Text:gsub('ض','ﺿ̭͠')
jack6= jack6:gsub('ص','ﺻ͡')
jack6= jack6:gsub('ث','ﺜ̲')
jack6= jack6:gsub('ق','ﭰ')
jack6= jack6:gsub('ف','ﻓ̲')
jack6= jack6:gsub('غ','ﻏ̲')
jack6= jack6:gsub('ع','ﻌ̲')
jack6= jack6:gsub('ه','ﮬ̲̌')
jack6= jack6:gsub('خ','خٌ')
jack6= jack6:gsub('ح','ﺣ̅')
jack6= jack6:gsub('ج','جُ')
jack6= jack6:gsub('د','ډ̝')
jack6= jack6:gsub('ذ','ذً')
jack6= jack6:gsub('ش','ﺷ̲')
jack6= jack6:gsub('س','ﺳ̉')
jack6= jack6:gsub('ي','ﯾ̃̐')
jack6= jack6:gsub('ب','ﺑ̲')
jack6= jack6:gsub('ل','ا̄ﻟ')
jack6= jack6:gsub('ا','ﺈ̃')
jack6= jack6:gsub('ت','ټُ')
jack6= jack6:gsub('ن','ﻧ̲')
jack6= jack6:gsub('م','ﻣ̲̉')
jack6= jack6:gsub('ك','گ')
jack6= jack6:gsub('ط','ﻁ̲')
jack6= jack6:gsub('ئ',' ْٰئ')
jack6= jack6:gsub('ء','ء')
jack6= jack6:gsub('ؤ','ؤ')
jack6= jack6:gsub('ر','ہڕ')
jack6= jack6:gsub('لا','ﻟ̲ﺂ̲')
jack6= jack6:gsub('ى','ى')
jack6= jack6:gsub('ة','ة')
jack6= jack6:gsub('و','ۇۈۉ')
jack6= jack6:gsub('ز','زُ')
jack6= jack6:gsub('ظ','ﻇ̲')
jack6= jack6:gsub('q','ǫ')
jack6= jack6:gsub('Q','ǫ')
jack6= jack6:gsub('w','ᴡ')
jack6= jack6:gsub('W','ᴡ')
jack6= jack6:gsub('e','ᴇ')
jack6= jack6:gsub('E','ᴇ')
jack6= jack6:gsub('r','ʀ')
jack6= jack6:gsub('R','ʀ')
jack6= jack6:gsub('t','ᴛ')
jack6= jack6:gsub('T','ᴛ')
jack6= jack6:gsub('y','ʏ')
jack6= jack6:gsub('Y','ʏ')
jack6= jack6:gsub('u','ụ')
jack6= jack6:gsub('U','ụ')
jack6= jack6:gsub('i','ɪ')
jack6= jack6:gsub('I','ɪ')
jack6= jack6:gsub('o','ᴏ')
jack6= jack6:gsub('O','ᴏ')
jack6= jack6:gsub('p','ᴘ')
jack6= jack6:gsub('P','ᴘ')
jack6= jack6:gsub('a','ᴀ')
jack6= jack6:gsub('A','ᴀ')
jack6= jack6:gsub('s','ѕ')
jack6= jack6:gsub('S','ѕ')
jack6= jack6:gsub('d','ᴅ')
jack6= jack6:gsub('D','ᴅ')
jack6= jack6:gsub('f','ғ')
jack6= jack6:gsub('F','ғ')
jack6= jack6:gsub('g','ɢ')
jack6= jack6:gsub('G','ɢ')
jack6= jack6:gsub('h','ʜ')
jack6= jack6:gsub('H','ʜ')
jack6= jack6:gsub('j','ᴊ')
jack6= jack6:gsub('J','ᴊ')
jack6= jack6:gsub('K','ᴋ')
jack6= jack6:gsub('k','ᴋ')
jack6= jack6:gsub('L','ʟ')
jack6= jack6:gsub('l','ʟ')
jack6= jack6:gsub('z','ᴢ')
jack6= jack6:gsub('Z','ᴢ')
jack6= jack6:gsub('x','х')
jack6= jack6:gsub('X','х')
jack6= jack6:gsub('c','ᴄ')
jack6= jack6:gsub('C','ᴄ')
jack6= jack6:gsub('v','ᴠ')
jack6= jack6:gsub('V','ᴠ')
jack6= jack6:gsub('b','ʙ')
jack6= jack6:gsub('B','ʙ')
jack6= jack6:gsub('n','ɴ')
jack6= jack6:gsub('N','ɴ')
jack6= jack6:gsub('m','ᴍ')
jack6= jack6:gsub('M','ᴍ')



local jack7= Text:gsub('ض','ﺿ')
jack7= jack7:gsub('ص','ﺻ')
jack7= jack7:gsub('ث','ﭥ')
jack7= jack7:gsub('ق','ﻗ̮ـ̃')
jack7= jack7:gsub('ف','ﭬ')
jack7= jack7:gsub('غ','ﻏ̣̐')
jack7= jack7:gsub('ع','ﻋ')
jack7= jack7:gsub('ه','ھَہّ')
jack7= jack7:gsub('خ','ﺧ')
jack7= jack7:gsub('ح','פ')
jack7= jack7:gsub('ج','ﭴ')
jack7= jack7:gsub('د','ﮃ')
jack7= jack7:gsub('ذ','ذ')
jack7= jack7:gsub('ش','ﺷ')
jack7= jack7:gsub('س','ﺳ')
jack7= jack7:gsub('ي','ﯾ')
jack7= jack7:gsub('ب','ﺑ')
jack7= jack7:gsub('ل','ﻟ')
jack7= jack7:gsub('ا','ﺂ')
jack7= jack7:gsub('ت','ﭠ')
jack7= jack7:gsub('ن','ﻧ')
jack7= jack7:gsub('م','ﻣ̝̚')
jack7= jack7:gsub('ك','گـ')
jack7= jack7:gsub('ط','ﻁْ')
jack7= jack7:gsub('ئ','ٰئـ')
jack7= jack7:gsub('ء','ء')
jack7= jack7:gsub('ؤ','ﯗ')
jack7= jack7:gsub('ر','ړُ')
jack7= jack7:gsub('لا','ﻟآ')
jack7= jack7:gsub('ى','ـﮯ')
jack7= jack7:gsub('ة','ة')
jack7= jack7:gsub('و','ۆ')
jack7= jack7:gsub('ز','ژ')
jack7= jack7:gsub('ظ','ﻅ')
jack7= jack7:gsub('q','𝘘')
jack7= jack7:gsub('Q','𝘘')
jack7= jack7:gsub('w','𝘞')
jack7= jack7:gsub('W','𝘞')
jack7= jack7:gsub('e','𝘌')
jack7= jack7:gsub('E','𝘌')
jack7= jack7:gsub('r','𝘙')
jack7= jack7:gsub('R','𝘙')
jack7= jack7:gsub('t','𝘛')
jack7= jack7:gsub('T','𝘛')
jack7= jack7:gsub('y','𝘠')
jack7= jack7:gsub('Y','𝘠')
jack7= jack7:gsub('u','𝘜')
jack7= jack7:gsub('U','𝘜')
jack7= jack7:gsub('i','𝘐')
jack7= jack7:gsub('I','𝘐')
jack7= jack7:gsub('o','𝘖')
jack7= jack7:gsub('O','𝘖')
jack7= jack7:gsub('p','𝘗')
jack7= jack7:gsub('P','𝘗')
jack7= jack7:gsub('a','𝘈')
jack7= jack7:gsub('A','𝘈')
jack7= jack7:gsub('s','𝘚')
jack7= jack7:gsub('S','𝘚')
jack7= jack7:gsub('d','𝘋')
jack7= jack7:gsub('D','𝘋')
jack7= jack7:gsub('f','𝘍')
jack7= jack7:gsub('F','𝘍')
jack7= jack7:gsub('g','𝘎')
jack7= jack7:gsub('G','𝘎')
jack7= jack7:gsub('h','𝘏')
jack7= jack7:gsub('H','𝘏')
jack7= jack7:gsub('j','𝘑')
jack7= jack7:gsub('J','𝘑')
jack7= jack7:gsub('k','𝘒')
jack7= jack7:gsub('K','𝘒')
jack7= jack7:gsub('L','𝘓')
jack7= jack7:gsub('l','𝘓')
jack7= jack7:gsub('z','𝘡')
jack7= jack7:gsub('Z','𝘡')
jack7= jack7:gsub('x','𝘟')
jack7= jack7:gsub('X','𝘟')
jack7= jack7:gsub('c','𝘊')
jack7= jack7:gsub('C','𝘊')
jack7= jack7:gsub('v','𝘝')
jack7= jack7:gsub('V','𝘝')
jack7= jack7:gsub('b','𝘉')
jack7= jack7:gsub('B','𝘉')
jack7= jack7:gsub('n','𝘕')
jack7= jack7:gsub('N','𝘕')
jack7= jack7:gsub('m','𝘔')
jack7= jack7:gsub('M','𝘔')



local jack8= Text:gsub('ض','ض');
jack8= jack8:gsub('ص','صہٰ')
jack8= jack8:gsub('ث','ثہٰـ')
jack8= jack8:gsub('ق','قہٰ')
jack8= jack8:gsub('ف','فہٰ')
jack8= jack8:gsub('غ','غـْ')
jack8= jack8:gsub('ع','ع')
jack8= jack8:gsub('ه','هٰہٰٖ')
jack8= jack8:gsub('خ','خخَـ')
jack8= jack8:gsub('ح','حہٰ')
jack8= jack8:gsub('ج','ججہٰ')
jack8= jack8:gsub('د','دَ')
jack8= jack8:gsub('ذ','ذّ')
jack8= jack8:gsub('ش','ششہٰ')
jack8= jack8:gsub('س','سہٰ')
jack8= jack8:gsub('ي','يٰ')
jack8= jack8:gsub('ب','بٰٰ')
jack8= jack8:gsub('ل','لہٰ')
jack8= jack8:gsub('ا','آ')
jack8= jack8:gsub('ت','تہٰ')
jack8= jack8:gsub('ن','نہٰ')
jack8= jack8:gsub('م','مہٰ')
jack8= jack8:gsub('ك','ككہٰ')
jack8= jack8:gsub('ط','طہٰ')
jack8= jack8:gsub('ئ',' ْئٰ')
jack8= jack8:gsub('ء','ء')
jack8= jack8:gsub('ؤ','ؤؤَ')
jack8= jack8:gsub('ر','رَ')
jack8= jack8:gsub('لا','لہٰا')
jack8= jack8:gsub('ى','ىہٰ')
jack8= jack8:gsub('ة','ة')
jack8= jack8:gsub('و','ہٰو')
jack8= jack8:gsub('ز','ز')
jack8= jack8:gsub('ظ','ظہٰ')
jack8= jack8:gsub('q','𝚀')
jack8= jack8:gsub('Q','𝚀')
jack8= jack8:gsub('w','𝚆')
jack8= jack8:gsub('W','𝚆')
jack8= jack8:gsub('e','𝙴')
jack8= jack8:gsub('E','𝙴')
jack8= jack8:gsub('r','𝚁')
jack8= jack8:gsub('R','𝚁')
jack8= jack8:gsub('t','𝚃')
jack8= jack8:gsub('T','𝚃')
jack8= jack8:gsub('y','𝚈')
jack8= jack8:gsub('Y','𝚈')
jack8= jack8:gsub('u','𝚄')
jack8= jack8:gsub('U','𝚄')
jack8= jack8:gsub('i','𝙸')
jack8= jack8:gsub('I','𝙸')
jack8= jack8:gsub('o','𝙾')
jack8= jack8:gsub('O','𝙾')
jack8= jack8:gsub('p','𝙿')
jack8= jack8:gsub('P','𝙿')
jack8= jack8:gsub('a','𝙰')
jack8= jack8:gsub('A','𝙰')
jack8= jack8:gsub('s','𝚂')
jack8= jack8:gsub('S','𝚂')
jack8= jack8:gsub('d','𝙳')
jack8= jack8:gsub('D','𝙳')
jack8= jack8:gsub('f','𝙵')
jack8= jack8:gsub('F','𝙵')
jack8= jack8:gsub('g','𝙶')
jack8= jack8:gsub('G','𝙶')
jack8= jack8:gsub('h','𝙷')
jack8= jack8:gsub('H','𝙷')
jack8= jack8:gsub('j','𝙹')
jack8= jack8:gsub('J','𝙹')
jack8= jack8:gsub('k','𝙺')
jack8= jack8:gsub('K','𝙺')
jack8= jack8:gsub('L','𝙻')
jack8= jack8:gsub('l','𝙻')
jack8= jack8:gsub('z','𝚉')
jack8= jack8:gsub('Z','𝚉')
jack8= jack8:gsub('x','𝚇')
jack8= jack8:gsub('X','𝚇')
jack8= jack8:gsub('c','𝙲')
jack8= jack8:gsub('C','𝙲')
jack8= jack8:gsub('v','𝚅')
jack8= jack8:gsub('V','𝚅')
jack8= jack8:gsub('b','𝙱')
jack8= jack8:gsub('B','𝙱')
jack8= jack8:gsub('n','𝙽')
jack8= jack8:gsub('N','𝙽')
jack8= jack8:gsub('m','𝙼')
jack8= jack8:gsub('M','𝙼')



local jack9= Text:gsub('ض','ض')
jack9= jack9:gsub('ص','ص')
jack9= jack9:gsub('ث','ث')
jack9= jack9:gsub('ق','قٌ')
jack9= jack9:gsub('ف','فُ')
jack9= jack9:gsub('غ','غ')
jack9= jack9:gsub('ع','عٍ')
jack9= jack9:gsub('ه','هـ')
jack9= jack9:gsub('خ','خـ')
jack9= jack9:gsub('ح','حٍ')
jack9= jack9:gsub('ج','جٍ')
jack9= jack9:gsub('د','دِ')
jack9= jack9:gsub('ذ','ذَ')
jack9= jack9:gsub('ش','شُ')
jack9= jack9:gsub('س','س')
jack9= jack9:gsub('ي','ي')
jack9= jack9:gsub('ب','بَ')
jack9= jack9:gsub('ل','لُِ')
jack9= jack9:gsub('ا','آ')
jack9= jack9:gsub('ت','ت')
jack9= jack9:gsub('ن','ن')
jack9= jack9:gsub('م','م')
jack9= jack9:gsub('ك','ڪ')
jack9= jack9:gsub('ط','طُ')
jack9= jack9:gsub('ئ','ئ ْٰ')
jack9= jack9:gsub('ء','ء')
jack9= jack9:gsub('ؤ','ؤ')
jack9= jack9:gsub('ر','ر')
jack9= jack9:gsub('لا','لُِآ')
jack9= jack9:gsub('ى','ىْ')
jack9= jack9:gsub('ة','ة')
jack9= jack9:gsub('و','وو')
jack9= jack9:gsub('ز','ز')
jack9= jack9:gsub('ظ','ظهُ')
jack9= jack9:gsub('q','ℚ')
jack9= jack9:gsub('Q','ℚ')
jack9= jack9:gsub('w','𝕎')
jack9= jack9:gsub('W','𝕎')
jack9= jack9:gsub('e','𝔼')
jack9= jack9:gsub('E','𝔼')
jack9= jack9:gsub('r','ℝ')
jack9= jack9:gsub('R','ℝ')
jack9= jack9:gsub('t','𝕋')
jack9= jack9:gsub('T','𝕋')
jack9= jack9:gsub('y','𝕐')
jack9= jack9:gsub('Y','𝕐')
jack9= jack9:gsub('u','𝕌')
jack9= jack9:gsub('U','𝕌')
jack9= jack9:gsub('i','𝕀')
jack9= jack9:gsub('I','𝕀')
jack9= jack9:gsub('o','𝕆')
jack9= jack9:gsub('O','𝕆')
jack9= jack9:gsub('p','ℙ')
jack9= jack9:gsub('P','ℙ')
jack9= jack9:gsub('a','𝔸')
jack9= jack9:gsub('A','𝔸')
jack9= jack9:gsub('s','𝕊')
jack9= jack9:gsub('S','𝕊')
jack9= jack9:gsub('d','𝔻')
jack9= jack9:gsub('D','𝔻')
jack9= jack9:gsub('f','𝔽')
jack9= jack9:gsub('F','𝔽')
jack9= jack9:gsub('g','𝔾')
jack9= jack9:gsub('G','𝔾')
jack9= jack9:gsub('h','ℍ')
jack9= jack9:gsub('H','ℍ')
jack9= jack9:gsub('j','𝕁')
jack9= jack9:gsub('J','𝕁')
jack9= jack9:gsub('k','𝕂')
jack9= jack9:gsub('K','𝕂')
jack9= jack9:gsub('L','𝕃')
jack9= jack9:gsub('l','𝕃')
jack9= jack9:gsub('z','ℤ')
jack9= jack9:gsub('Z','ℤ')
jack9= jack9:gsub('x','𝕏')
jack9= jack9:gsub('X','𝕏')
jack9= jack9:gsub('c','ℂ')
jack9= jack9:gsub('C','ℂ')
jack9= jack9:gsub('v','𝕍')
jack9= jack9:gsub('V','𝕍')
jack9= jack9:gsub('b','𝔹')
jack9= jack9:gsub('B','𝔹')
jack9= jack9:gsub('n','ℕ')
jack9= jack9:gsub('N','ℕ')
jack9= jack9:gsub('m','𝕄')
jack9= jack9:gsub('M','𝕄')


local Text_jacka = "1- `"..jack..EmojeS[math.random(#EmojeS)]
.."`\n\n2- `"..jack2..EmojeS[math.random(#EmojeS)]
.."`\n\n3- `"..jack3..EmojeS[math.random(#EmojeS)]
.."`\n\n4- `"..jack4..EmojeS[math.random(#EmojeS)]
.."`\n\n5- `"..jack5..EmojeS[math.random(#EmojeS)]
.."`\n\n6- `"..jack6..EmojeS[math.random(#EmojeS)]
.."`\n\n7- `"..jack7..EmojeS[math.random(#EmojeS)]
.."`\n\n8- `"..jack8..Emoje[math.random(#Emoje)]
.."`\n\n9- `"..jack9..Emoje[math.random(#Emoje)]
.."`\n\n10- `"..jack5..Emoje[math.random(#Emoje)]
Text_jacka = Text_jacka.."`\n\n| اضغـط علـي الاسـم ليتـم النـسخ  \n★"
sendMsg(msg.chat_id_,msg.id_,Text_jacka)
return false
end



end

return {
debo = {
"^(زخرفه)$"
 },
 idebo = jacka,
 ddebo = TextRes,
 }
 
 

--[[
███████▀ │DEBO ﹏  @V_P_E
│تم تطوير وبرمجة السورس من قبل جاك ✺
│@ DEBO_TEAM_3
#-------------------------------------------------------------------
]]
